// data-vocab.js
// Complete Koine Greek Vocabulary List (cleaned + normalized accents/breathings)

export const VOCAB = [
  { g: "ἅγγελος", e: "angel, messenger" },
  { g: "ἀμήν", e: "amen" },
  { g: "ἄνθρωπος", e: "man, mankind" },
  { g: "ἀπόστολος", e: "apostle" },
  { g: "Γαλιλαία", e: "galilee" },
  { g: "γραφή", e: "writing" },
  { g: "δόξα", e: "glory, majesty, fame" },
  { g: "ἐγώ", e: "I" },
  { g: "ἔσχατος", e: "last" },
  { g: "ζωή", e: "life" },
  { g: "θεός", e: "God" },
  { g: "καί", e: "and, even, also, namely" },
  { g: "καρδία", e: "heart, inner self" },
  { g: "κόσμος", e: "world, universe, mankind" },
  { g: "λόγος", e: "word, Word, statement, message" },
  { g: "πνεῦμα", e: "spirit, Spirit, wind, breath, inner self" },
  { g: "προφήτης", e: "prophet" },
  { g: "σάββατον", e: "sabbath" },
  { g: "φωνή", e: "sound, noise, voice" },
  { g: "χριστός", e: "Christ, Messiah, Anointed One" },
  { g: "ἀγάπη", e: "love" },
  { g: "ἄλλος", e: "other, another" },
  { g: "αὐτός", e: "singular: he, she, it (him, her); plural: they (them)" },
  { g: "βασιλεία", e: "kingdom" },
  { g: "δέ", e: "but, and" },
  { g: "ἐν", e: "in, on, among" },
  { g: "ἔργον", e: "work, deed, action" },
  { g: "καιρός", e: "(appointed) time, season" },
  { g: "νῦν", e: "adverb: now; noun: the present" },
  { g: "ὁ, ἡ, τό", e: "the" },
  { g: "ὅτι", e: "that, since, because" },
  { g: "οὐ", e: "not" },
  { g: "ὥρα", e: "hour, occasion, moment" },
  { g: "ἁμαρτία", e: "sin" },
  { g: "ἀρχή", e: "beginning; ruler" },
  { g: "γάρ", e: "for; then" },
  { g: "εἶπεν", e: "he/she/it said" },
  { g: "εἰς", e: "into; in" },
  { g: "ἐξουσία", e: "authority, power" },
  { g: "εὐαγγέλιον", e: "good news, Gospel" },
  { g: "Ἰησοῦς", e: "Jesus, Joshua" },
  { g: "κύριος", e: "Lord; lord, master, sir" },
  { g: "μή", e: "not, lest" },
  { g: "οὐρανός", e: "heaven; sky" },
  { g: "οὗτος, αὕτη, τοῦτο", e: "singular: this (one); plural: these" },
  { g: "σύ", e: "you (singular)" },
  { g: "υἱός", e: "son; descendant" },
  { g: "ὥστε", e: "therefore, so that" },
  { g: "ἀλλά (ἀλλ᾽)", e: "but, yet; rather" },
  { g: "ἀπό (ἀπ᾽, ἀφ᾽)", e: "gen: (away) from" },
  { g: "διά (δι᾽)", e: "gen: through; acc: on account of" },
  { g: "εἰμί", e: "I am, exist, live, am present" },
  { g: "ἐκ (ἐξ)", e: "gen: from, out of" },
  { g: "ἡμέρα", e: "day" },
  { g: "ἦν", e: "he/she/it was" },
  { g: "θάλασσα", e: "sea, lake" },
  { g: "θάνατος", e: "death" },
  { g: "ἵνα", e: "in order that; that; so that" },
  { g: "Ἰωάννης", e: "John" },
  { g: "λέγω", e: "I say, speak" },
  { g: "μετά (μετ᾽, μεθ᾽)", e: "gen: with; acc: after" },
  { g: "οἰκία", e: "house, home" },
  { g: "οἶκος", e: "house, home" },
  { g: "ὄχλος", e: "crowd, multitude" },
  { g: "παρά (παρ᾽)", e: "gen: from; dat: beside, in the presence of; acc: alongside of" },
  { g: "παραβολή", e: "parable" },
  { g: "πρός", e: "acc: to, towards; with" },
  { g: "ὑπό (ὑπ᾽, ὑφ᾽)", e: "gen: by; acc: under" },
  { g: "εἰς", e: "acc: into, in; among" },
  { g: "ἐν", e: "dat: in, on, among" },
  { g: "ἀγαθός", e: "good, useful" },
  { g: "ἀγαπητός", e: "beloved" },
  { g: "ἅγιος", e: "adjective: holy; plural noun: saints" },
  { g: "αἰώνιος", e: "eternal" },
  { g: "ἀλλήλων", e: "one another" },
  { g: "ἀπεκρίθη", e: "he/she/it answered" },
  { g: "δοῦλος", e: "slave; servant" },
  { g: "ἐάν", e: "if; when" },
  { g: "ἐμός, ἐμή, ἐμόν", e: "my, mine" },
  { g: "ἐντολή", e: "commandment" },
  { g: "καθώς", e: "as, even as" },
  { g: "κακός", e: "bad, evil" },
  { g: "μου (ἐμοῦ)", e: "my" },
  { g: "νεκρός", e: "adjective: dead; noun: dead body, corpse" },
  { g: "πιστός", e: "faithful, believing" },
  { g: "πονηρός", e: "evil, bad" },
  { g: "πρῶτος", e: "first; earlier" },
  { g: "τρίτος", e: "third" },
  { g: "εἰ", e: "if" },
  { g: "εἰ μή", e: "except; if not" },
  { g: "εἷς, μία, ἕν", e: "one" },
  { g: "ἤδη", e: "now, already" },
  { g: "ὄνομα, –ατος, τό", e: "name; reputation" },
  { g: "οὐδείς, οὐδεμία, οὐδέν", e: "no one, none, nothing" },
  { g: "πᾶς, πᾶσα, πᾶν", e: "singular: each, every; plural: all" },
  { g: "περί", e: "genitive: concerning, about; accusative: around" },
  { g: "σάρξ, σαρκός, ἡ", e: "flesh; body" },
  { g: "σύν", e: "dative: with" },
  { g: "σῶμα, –ατος, τό", e: "body" },
  { g: "τέκνον, –ου, τό", e: "child; descendant" },
  { g: "τίς, τί", e: "Who? What? Which? Why?" },
  { g: "τις, τι", e: "Someone/thing; certain one/thing; anyone/thing" },
  { g: "πνεῦμα, —ατος, τό", e: "spirit, Spirit" },
  { g: "Σίμων, —ωνος, ὁ", e: "Simon" },
  { g: "ἀδελφός, οῦ, ὁ", e: "brother" },
  { g: "ἄν", e: "“-ever”" },
  { g: "ἀνήρ, ἀνδρός, ὁ", e: "male; husband; man" },
  { g: "ἐκκλησία, ας, ἡ", e: "a church; (the) Church; assembly, congregation" },
  { g: "ἐλπίς, ίδος, ἡ", e: "hope, expectation" },
  { g: "ἔξω", e: "adverb: without; preposition (gen): outside" },
  { g: "ἐπί (ἐπ᾽, ἐφ᾽)", e: "gen: on, over, when; dat: on the basis of, at; acc: on, to, against" },
  { g: "ἡμεῖς", e: "we" },
  { g: "θέλημα, θελήματος, τό", e: "will, desire" },
  { g: "ἴδε", e: "See! Behold!" },
  { g: "ἰδού", e: "See! Behold!" },
  { g: "καλός, ή, όν", e: "good; beautiful" },
  { g: "μήτηρ, μητρός, ἡ", e: "mother" },
  { g: "οὐδέ", e: "and, not, not even; neither, nor" },
  { g: "πατήρ, πατρός, ὁ", e: "father" },
  { g: "πίστις, πίστεως, ἡ", e: "faith, belief; trust, “teaching” in that what is believed" },
  { g: "ὕδωρ, ὕδατος, τό", e: "water" },
  { g: "ὑμεῖς", e: "you (plural)" },
  { g: "φῶς, φωτός, τό", e: "light" },
  { g: "χάρις, χάριτος, ἡ", e: "grace, favor, kindness" },
  { g: "ὧδε", e: "here" },
  { g: "αἰών, ῶνος, ὁ", e: "age, eternity" },
  { g: "διδάσκαλος, ου, ὁ", e: "teacher" },
  { g: "εὐθύς", e: "immediately" },
  { g: "ἕως", e: "conj: until; preposition (gen): as far as" },
  { g: "μαθητής, οῦ, ὁ", e: "disciple" },
  { g: "μέν", e: "on the one hand; indeed" },
  { g: "μηδείς, μηδεμία, μηδέν", e: "no one/thing" },
  { g: "μόνος, η, ον", e: "alone, only" },
  { g: "ὅπως", e: "how; (in order) that" },
  { g: "ὅσος, η, ον", e: "as great as, as many as" },
  { g: "οὖν", e: "therefore, accordingly; then" },
  { g: "ὀφθαλμός, οῦ, ὁ", e: "eye, sight" },
  { g: "πάλιν", e: "again" },
  { g: "πούς, ποδός, ὁ", e: "foot" },
  { g: "ὑπέρ", e: "gen: in behalf of; acc: above" },
  { g: "γυνή, γυναικός, ἡ", e: "woman; wife" },
  { g: "δικαιοσύνη", e: "righteousness" },
  { g: "δώδεκα", e: "twelve" },
  { g: "ἑαυτοῦ, ῆς, οῦ", e: "sing: himself/herself/itself; pl: themselves" },
  { g: "ἐκεῖνος, η, ο", e: "sing: that man/woman/thing; pl: those men/women/things" },
  { g: "ἤ", e: "or; than" },
  { g: "κἀγώ", e: "and I; but I" },
  { g: "μακάριος, ία, ιον", e: "blessed, happy" },
  { g: "μέγας, μεγάλη, μέγα", e: "large; great" },
  { g: "πόλις, εως, ἡ", e: "city, town" },
  { g: "πολύς, πολλή, πολύ", e: "sing: much; pl: many; adverb: often" },
  { g: "πῶς", e: "how?" },
  { g: "σημεῖον", e: "sign, miracle" },
  { g: "ἀλήθεια", e: "truth" },
  { g: "εἰρήνη", e: "peace" },
  { g: "ἐνώπιον", e: "gen: before" },
  { g: "ἐπαγγελία", e: "promise" },
  { g: "ἑπτά", e: "seven" },
  { g: "θρόνος", e: "throne" },
  { g: "Ἰερουσαλήμ, ἡ", e: "Jerusalem" },
  { g: "κατά (κατ᾽, καθ᾽)", e: "gen: down from, against; acc: according to, throughout, during" },
  { g: "κεφαλή", e: "head" },
  { g: "ὁδός", e: "way, road; journey, conduct" },
  { g: "ὃς, ἣ, ὃ", e: "who (whom), which" },
  { g: "ὅτε", e: "when" },
  { g: "οὕτως", e: "thus, so; in this manner" },
  { g: "πλοῖον", e: "ship, boat" },
  { g: "ῥῆμα, ατος, τό", e: "word, saying" },
  { g: "τέ", e: "and (so), so" },
  { g: "χείρ, χειρός, ἡ", e: "hand" },
  { g: "ψυχή", e: "life; soul; self" },

  { g: "ἀκούω", e: "I hear; learn, obey; understand" },
  { g: "βλέπω", e: "I see, look at" },
  { g: "ἔχω", e: "I have, hold" },
  { g: "λέγω", e: "I say, speak" },
  { g: "λύω", e: "I loose, untie, destroy" },
  { g: "νόμος, ου, ὁ", e: "law; principle" },
  { g: "ὅπου", e: "where" },
  { g: "πιστεύω", e: "I believe, have faith (in), trust" },
  { g: "πρόσωπον, ου, τό", e: "face; appearance" },
  { g: "τότε", e: "then; thereafter" },
  { g: "τυφλός, ή, όν", e: "blind" },
  { g: "χαρά, ᾶς, ἡ", e: "joy, delight" },
  { g: "ἀγαπάω", e: "I love, cherish" },
  { g: "δαιμόνιον, ου, τό", e: "demon" },
  { g: "ζητέω", e: "I seek, desire, try to obtain" },
  { g: "καλέω", e: "I call, name, invite" },
  { g: "λαλέω", e: "I speak, say" },
  { g: "οἶδα", e: "I know, understand" },
  { g: "ὅταν", e: "whenever" },
  { g: "πλείων, πλεῖον", e: "larger, more" },
  { g: "πληρόω", e: "I fill, complete, fulfill" },
  { g: "ποιέω", e: "I do, make" },
  { g: "τηρέω", e: "I keep, guard, observe" },
  { g: "ἀποκρίνομαι", e: "I answer" },
  { g: "δεῖ", e: "it is necessary" },
  { g: "δύναμαι", e: "I am able, am powerful" },
  { g: "ἔρχομαι", e: "I come, go" },
  { g: "νύξ, νυκτός, ἡ", e: "night" },
  { g: "ὅστις, ἥτις, ὅτι", e: "whoever, whichever, whatever" },
  { g: "πορεύομαι", e: "I go, proceed; live" },
  { g: "συνάγω", e: "I gather together, bring together; lead" },
  { g: "τόπος", e: "place; location" },
  { g: "ὡς", e: "as, like; that; approximately; when, after" },
  { g: "βασιλεύς, έως, ὁ", e: "king" },
  { g: "γεννάω", e: "I beget, give birth to; produce" },
  { g: "ζάω", e: "I live" },
  { g: "Ἰουδαία", e: "Judea" },
  { g: "Ἰουδαῖος, αία, αῖον", e: "adjective: Jewish; noun: Jew" },
  { g: "Ἰσραήλ", e: "Israel" },
  { g: "καρπός", e: "fruit; crop; result" },
  { g: "μείζων", e: "greater" },
  { g: "ὅλος, η, ον", e: "adjective: whole, complete; adverb: entirely" },
  { g: "προσκυνέω", e: "I worship" },
  { g: "αἴρω", e: "I raise, take up, take away" },
  { g: "ἀποκτείνω", e: "I kill" },
  { g: "ἀποστέλλω", e: "I send (away)" },
  { g: "βαπτίζω", e: "I baptize; dip, immerse" },
  { g: "γινώσκω", e: "I know, come to know, realize, learn" },
  { g: "γλῶσσα, —ης, ἡ", e: "tongue, language" },
  { g: "ἐγείρω", e: "I raise up, wake" },
  { g: "ἐκβάλλω", e: "I cast out, send out" },
  { g: "ἐκεῖ", e: "there, in that place" },
  { g: "κρίνω", e: "I judge, decide, prefer" },
  { g: "λαός, —οῦ, ὁ", e: "people, crowd" },
  { g: "μένω", e: "I remain, live" },
  { g: "ὁράω", e: "I see, notice, experience" },
  { g: "σοφία, —ας, ἡ", e: "wisdom" },
  { g: "στόμα, —ατος, τό", e: "mouth" },
  { g: "σῴζω", e: "I save, deliver, rescue" },

  { g: "ἀκολουθέω", e: "I follow; accompany" },
  { g: "διδάσκω", e: "I teach" },
  { g: "ἐπερωτάω", e: "I ask (for)" },
  { g: "ἐρωτάω", e: "I ask; request" },
  { g: "θέλω", e: "I wish, desire; enjoy" },
  { g: "περιπατέω", e: "I walk (around); live" },
  { g: "συναγωγή", e: "synagogue; meeting" },
  { g: "φαρισαῖος", e: "Pharisee" },
  { g: "χρόνος", e: "time" },
  { g: "ἀποθνῄσκω", e: "I die, am about to die, am freed from" },
  { g: "ἄρτος", e: "bread, loaf, food" },
  { g: "βάλλω", e: "I throw" },
  { g: "γῆ, γῆς, ἡ", e: "earth, land, region, humanity" },
  { g: "γίνομαι", e: "I become, take place; am, exist; am born, am created" },
  { g: "εἰσέρχομαι", e: "I come in(to); go in(to); enter" },
  { g: "ἐξέρχομαι", e: "I go out" },
  { g: "ἔτι", e: "still, yet, even" },
  { g: "εὑρίσκω", e: "I find" },
  { g: "λαμβάνω", e: "I take; receive" },
  { g: "οὔτε", e: "And not, neither, nor" },
  { g: "προσέρχομαι", e: "I come/go to" },
  { g: "προσεύχομαι", e: "I pray" },
  { g: "πῦρ, πυρός, τό", e: "fire" },
  { g: "ἀπέρχομαι", e: "I depart" },
  { g: "ἄρχομαι", e: "I begin" },
  { g: "γράφω", e: "I write" },
  { g: "διό", e: "Therefore, for this reason" },
  { g: "δοξάζω", e: "I praise, honor, glorify" },
  { g: "δύναμις", e: "power; miracle" },
  { g: "κηρύσσω", e: "I proclaim; preach" },
  { g: "πίνω", e: "I drink" },
  { g: "ἄγω", e: "I lead, bring, arrest" },
  { g: "αἷμα", e: "blood" },
  { g: "ἕκαστος", e: "each, every" },
  { g: "ἱμάτιον", e: "garment, cloak" },
  { g: "ὄρος", e: "mountain, hill" },
  { g: "ὑπάγω", e: "I depart" },
  { g: "φοβέομαι", e: "I fear" },
  { g: "χαίρω", e: "I rejoice" },
  { g: "αἰτέω", e: "I ask; demand" },
  { g: "μᾶλλον", e: "more, rather" },
  { g: "μαρτυρέω", e: "I bear witness, testify" },
  { g: "ἀναβαίνω", e: "I go up" },
  { g: "ἀρχιερεύς, —έως, ὁ", e: "chief priest, high priest" },
  { g: "δεξιός, —ά, —όν", e: "right" },
  { g: "δύο", e: "two" },
  { g: "ἕτερος, —α, —ον", e: "other; another, different" },
  { g: "εὐαγγελίζω", e: "I bring good news; preach" },
  { g: "θεωρέω", e: "I look at; perceive" },
  { g: "Ἱεροσόλυμα, τά", e: "Jerusalem" },
  { g: "κάθημαι", e: "I sit (down); live" },
  { g: "καταβαίνω", e: "I go down; come down" },
  { g: "οὗ", e: "where" },
  { g: "παρακαλέω", e: "I call (to one’s side); urge, implore; comfort" },
  { g: "πείθω", e: "I persuade" },
  { g: "τρεῖς, τρία", e: "three" }
];
